# clean environment
rm(list=ls())

##############################################################
# Load libraries                                          ####
##############################################################

library(dplyr)
library(sensiPhy)
library(rr2)
library(ggplot2)
library(forcats)
library(ape)
library(ggpubr)
library(gt)
library(Cairo)

##############################################################
# Load data                                               ####
##############################################################

db <- read.csv('Data/Extant_mammals_species_PLRs.csv')

#remove taxa with not available BM and size ratio
db <- filter(db, Body_mass_island_taxon != "") 
db <- filter(db, Size_ratio != "") 
#remove taxa that experienced no substantial size change
db <- filter(db, Direction_body_size_change != "no_change")

#Reorder IUCN_Category from low to high extinction risk
db <- db %>%
  mutate(IUCN_Category =
           fct_relevel(IUCN_Category,
                       "LC",
                       "NT",
                       "VU",
                       "EN",
                       "CR"))

#Create threatened vs nonthreatened column
db <- db %>%
  mutate(Pr_threatened = recode_factor(IUCN_Category,
                                CR = "threatened",
                                EN = "threatened",
                                VU = "threatened",
                                NT = "nonthreatened",
                                LC = "nonthreatened"))

#Reorder threatened vs nonthreatened column from low to high extinction risk
db <- db %>%
  mutate(Pr_threatened =
           fct_relevel(Pr_threatened,
                       "nonthreatened",
                       "threatened"))

#Create threatened vs nonthreatened column as a binary output 
#0 = nonthreatened; 1 = threatened
db <- db %>%
  mutate(Pr_threatened_bin = recode(Pr_threatened,
                                    nonthreatened = 0L,
                                    threatened = 1L))

#########################################################
# Read trees: complete trees generated by TACT and   ####
# DNA-only trees                                     ####
#########################################################

trees_complete <- read.nexus('Results/TACT/100trees_outputs_TACT.trees')

trees_DNA_only <- read.nexus('Results/TACT/100_trees_DNA_only.trees')

#Assign rownames to dataset
rownames(db)=db$Latin_binomial

#############################################################################
# Fit PLR (Ives & Garland, 2010) for 2 main single predictor models      ####
# and run sensitivity analysis accounting for phylogenetic uncertainty   ####
# across 100 complete trees generated by TACT                            ####
#############################################################################

###################################################################
# Fit model and calculate summary stats for Magnitude_size_change #
###################################################################

PLR1 <- tree_phyglm(Pr_threatened_bin ~ Magnitude_body_size_change, data = db, phy = trees_complete, n.tree = 100)
summary(PLR1)
sensi_plot1 <- sensi_plot(PLR1, graphs = 3)
ggsave(sensi_plot1, filename = "PLR_P(threatened)_vs_Magnitude_body_size_change_extant_species_phylo_uncertainty_complete_trees_TACT.pdf", width = 6, height = 6, device = cairo_pdf) 

#Extract summary stats in a table
stats_PLR1 <- PLR1$all.stats
stats_PLR1 <- stats_PLR1 %>% mutate_if(is.numeric, round, digits=3)
rownames(stats_PLR1)[rownames(stats_PLR1) == "optpar"] <- "alpha"

#Calculate R2_lik and AICc across 100 complete trees generated by TACT
#Set up a list to store results
R2_PLR1 <- list(length = trees_complete) 
AICc_PLR1 <- list(length = trees_complete) 

#Function to calculate AICc (from https://github.com/mrhelmus/phylogeny_manipulation/blob/master/AIC_func.r)
AICc.phyloglm<-function(mod, return.K = FALSE, second.ord = TRUE, nobs = NULL, ...){
  
  if(identical(nobs, NULL)) {n <- length(mod$residuals)} else {n <- nobs}
  LL <- logLik(mod)$logLik
  K <- logLik(mod)$df  #extract correct number of parameters included in model - this includes LM
  if(second.ord == TRUE) {AICc <- -2*LL+2*K*(n/(n-K-1))}  else{AICc <- -2*LL+2*K}
  if(return.K == TRUE) AICc[1] <- K #attributes the first element of AICc to K
  return(AICc)
}

#Run the model fitting analysis on all trees, calculate for each one a R2.lik and AICc value and store the results in the list
for(i in 1:length(trees_complete)) {
  currentTree <- trees_complete[[i]]
  PLR_iterated <- phyloglm(Pr_threatened_bin ~ Magnitude_body_size_change, data = db, phy = currentTree, method = c("logistic_MPLE"), boot = 100)
  R2_PLR1[i] <- R2.lik(PLR_iterated)
  AICc_PLR1[i] <- AICc.phyloglm(PLR_iterated)
}

#transform list R2 in data frame
R2_PLR1_df <- data.frame(matrix(unlist(R2_PLR1), nrow=length(R2_PLR1), byrow=TRUE))
R2_PLR1_df <- rename(R2_PLR1_df, values = matrix.unlist.R2_PLR1...nrow...length.R2_PLR1...byrow...TRUE.)

#Calculate mean, max, min, sd and CIs of R2
R2_summary1 <- sapply(R2_PLR1_df, function(R2_PLR1_df) c( "min" = min(R2_PLR1_df), 
                         "max"= max(R2_PLR1_df),
                         "mean" = mean(R2_PLR1_df),
                         "sd_tree" = sd(R2_PLR1_df)))

Mean_ci_R2 <- mean_ci(R2_PLR1_df$values)
Mean_ci_R2 <- rename(Mean_ci_R2, mean = y)
Mean_ci_R2 <- rename(Mean_ci_R2, CI_low = ymin)
Mean_ci_R2 <- rename(Mean_ci_R2, CI_high = ymax)
rownames(Mean_ci_R2)[rownames(Mean_ci_R2) == "1"] <- "values"
R2_summary1 <- t(R2_summary1)
R2_summary1 <- as.data.frame(R2_summary1)
R2_summary1 <- merge(R2_summary1,Mean_ci_R2,by="mean")
rownames(R2_summary1)[rownames(R2_summary1) == "1"] <- "R2_lik"

#transform list AICc in data frame
AICc_PLR1_df <- data.frame(matrix(unlist(AICc_PLR1), nrow=length(AICc_PLR1), byrow=TRUE))
AICc_PLR1_df <- rename(AICc_PLR1_df, values = matrix.unlist.AICc_PLR1...nrow...length.AICc_PLR1...byrow...TRUE.)

#Calculate mean, max, min, sd and CIs of AICc
AICc_summary1 <- sapply(AICc_PLR1_df, function(AICc_PLR1_df) c( "min" = min(AICc_PLR1_df), 
                                                                  "max"= max(AICc_PLR1_df),
                                                                  "mean" = mean(AICc_PLR1_df),
                                                                  "sd_tree" = sd(AICc_PLR1_df)))

Mean_ci_AICc <- mean_ci(AICc_PLR1_df$values)
Mean_ci_AICc <- rename(Mean_ci_AICc, mean = y)
Mean_ci_AICc <- rename(Mean_ci_AICc, CI_low = ymin)
Mean_ci_AICc <- rename(Mean_ci_AICc, CI_high = ymax)
rownames(Mean_ci_AICc)[rownames(Mean_ci_AICc) == "1"] <- "values"
AICc_summary1 <- t(AICc_summary1)
AICc_summary1 <- as.data.frame(AICc_summary1)
AICc_summary1 <- merge(AICc_summary1,Mean_ci_AICc,by="mean")
rownames(AICc_summary1)[rownames(AICc_summary1) == "1"] <- "AICc"

#Add R2 and AICc to the other summ stats 
stats_PLR1 <- rbind(stats_PLR1, R2_summary1, AICc_summary1)
stats_PLR1
stats_PLR1 <- add_rownames(stats_PLR1, "VALUE")
stats_PLR1

#Convert in a table
gt_tbl1 <- gt(stats_PLR1)

gt_tbl1 <- gt_tbl1 %>% tab_header(
  title = "Model: P(threatened) ~ Magnitude of body mass change",
  subtitle = "n = 644; 100 complete TACT trees")

gt_tbl1

#Save the table
gtsave(gt_tbl1, "Table_Summ_stats_PLR_P(threatened)_vs_Magnitude_extant_species.html")

#######################################################
# Fit model and calculate summary stats for Body mass #
#######################################################

db$Body_mass_island_taxon <- scale(db$Body_mass_island_taxon) #scale BM
PLR2 <- tree_phyglm(Pr_threatened_bin ~ Body_mass_island_taxon, data = db, phy = trees_complete, n.tree = 100)
summary(PLR2)
sensi_plot2 <- sensi_plot(PLR2, graphs = 3)
ggsave(sensi_plot2, filename = "PLR_P(threatened)_vs_Body_mass_extant_species_phylo_uncertainty_complete_trees_TACT.pdf", width = 6, height = 6, device = cairo_pdf) 

#Extract summary stats in a table
stats_PLR2 <- PLR2$all.stats
stats_PLR2 <- stats_PLR2 %>% mutate_if(is.numeric, round, digits=3)
rownames(stats_PLR2)[rownames(stats_PLR2) == "optpar"] <- "alpha"

#Calculate R2_lik and AICc across 100 complete trees generated by TACT
#Set up a list to store results
R2_PLR2 <- list(length = trees_complete) 
AICc_PLR2 <- list(length = trees_complete) 

#Run the model fitting analysis on all trees, calculate for each one a R2.lik and AICc value and store the results in the list
for(i in 1:length(trees_complete)) {
  currentTree <- trees_complete[[i]]
  PLR_iterated <- phyloglm(Pr_threatened_bin ~ Body_mass_island_taxon, data = db, phy = currentTree, method = c("logistic_MPLE"), boot = 100)
  R2_PLR2[i] <- R2.lik(PLR_iterated)
  AICc_PLR2[i] <- AICc.phyloglm(PLR_iterated)
}

#transform list R2 in data frame
R2_PLR2_df <- data.frame(matrix(unlist(R2_PLR2), nrow=length(R2_PLR2), byrow=TRUE))

R2_PLR2_df <- rename(R2_PLR2_df, values = matrix.unlist.R2_PLR2...nrow...length.R2_PLR2...byrow...TRUE.)

#Calculate mean, max, min, sd and CIs of R2
R2_summary2 <- sapply(R2_PLR2_df, function(R2_PLR2_df) c( "min" = min(R2_PLR2_df), 
                                                            "max"= max(R2_PLR2_df),
                                                            "mean" = mean(R2_PLR2_df),
                                                            "sd_tree" = sd(R2_PLR2_df)))

Mean_ci_R2 <- mean_ci(R2_PLR2_df$values)
Mean_ci_R2 <- rename(Mean_ci_R2, mean = y)
Mean_ci_R2 <- rename(Mean_ci_R2, CI_low = ymin)
Mean_ci_R2 <- rename(Mean_ci_R2, CI_high = ymax)
rownames(Mean_ci_R2)[rownames(Mean_ci_R2) == "1"] <- "values"
R2_summary2 <- t(R2_summary2)
R2_summary2 <- as.data.frame(R2_summary2)
R2_summary2 <- merge(R2_summary2,Mean_ci_R2,by="mean")
rownames(R2_summary2)[rownames(R2_summary2) == "1"] <- "R2_lik"

#transform list AICc in data frame
AICc_PLR2_df <- data.frame(matrix(unlist(AICc_PLR2), nrow=length(AICc_PLR2), byrow=TRUE))
AICc_PLR2_df <- rename(AICc_PLR2_df, values = matrix.unlist.AICc_PLR2...nrow...length.AICc_PLR2...byrow...TRUE.)

#Calculate mean, max, min, sd and CIs of AICc
AICc_summary2 <- sapply(AICc_PLR2_df, function(AICc_PLR2_df) c( "min" = min(AICc_PLR2_df), 
                                                                  "max"= max(AICc_PLR2_df),
                                                                  "mean" = mean(AICc_PLR2_df),
                                                                  "sd_tree" = sd(AICc_PLR2_df)))

Mean_ci_AICc <- mean_ci(AICc_PLR2_df$values)
Mean_ci_AICc <- rename(Mean_ci_AICc, mean = y)
Mean_ci_AICc <- rename(Mean_ci_AICc, CI_low = ymin)
Mean_ci_AICc <- rename(Mean_ci_AICc, CI_high = ymax)
rownames(Mean_ci_AICc)[rownames(Mean_ci_AICc) == "1"] <- "values"
AICc_summary2 <- t(AICc_summary2)
AICc_summary2 <- as.data.frame(AICc_summary2)
AICc_summary2 <- merge(AICc_summary2,Mean_ci_AICc,by="mean")
rownames(AICc_summary2)[rownames(AICc_summary2) == "1"] <- "AICc"

#Add R2 and AICc to the other summ stats
stats_PLR2 <- rbind(stats_PLR2, R2_summary2, AICc_summary2)
stats_PLR2
stats_PLR2 <- add_rownames(stats_PLR2, "VALUE")
stats_PLR2

#Convert in a table
gt_tbl2 <- gt(stats_PLR2)

gt_tbl2 <- gt_tbl2 %>% tab_header(
  title = "Model: P(threatened) ~ Body mass (kg)",
  subtitle = "n = 644; 100 complete TACT trees")

gt_tbl2

#Save the table
gtsave(gt_tbl2, "Table_Summ_stats_PLR_P(threatened)_vs_Body_mass_extant_species.html")


#############################################################################
# Fit PLR (Ives & Garland, 2010) for 2 main single predictor models      ####
# and run sensitivity analysis accounting for phylogenetic uncertainty   ####
# across 100 DNA-only trees                                              ####
#############################################################################

###################################################################
# Fit model and calculate summary stats for Magnitude_size_change #
###################################################################

PLR1_DNA_only <- tree_phyglm(Pr_threatened_bin ~ Magnitude_body_size_change, data = db, phy = trees_DNA_only, n.tree = 100)
summary(PLR1_DNA_only)
sensi_plot3 <- sensi_plot(PLR1_DNA_only, graphs = 3)
ggsave(sensi_plot3, filename = "PLR_P(threatened)_vs_Magnitude_body_size_change_extant_species_phylo_uncertainty_trees_DNA_only.pdf", width = 6, height = 6, device = cairo_pdf) 

#Extract summary stats in a table
stats_PLR3 <- PLR1_DNA_only$all.stats
stats_PLR3 <- stats_PLR3 %>% mutate_if(is.numeric, round, digits=3)
rownames(stats_PLR3)[rownames(stats_PLR3) == "optpar"] <- "alpha"

#Calculate R2_lik and AICc across 100 DNA-only trees
#Set up a list to store results
R2_PLR3 <- list(length = trees_DNA_only)
AICc_PLR3 <- list(length = trees_DNA_only)

#Run the model fitting analysis on all trees, calculate for each one a R2.lik and AICc value and store the results in the list
for(i in 1:length(trees_DNA_only)) {
  currentTree <- trees_DNA_only[[i]]
  PLR_iterated <- phyloglm(Pr_threatened_bin ~ Magnitude_body_size_change, data = db, phy = currentTree, method = c("logistic_MPLE"), boot = 100)
  R2_PLR3[i] <- R2.lik(PLR_iterated)
  AICc_PLR3[i] <- AICc.phyloglm(PLR_iterated)
}

#transform list R2 in data frame
R2_PLR3_df <- data.frame(matrix(unlist(R2_PLR3), nrow=length(R2_PLR3), byrow=TRUE))
R2_PLR3_df <- rename(R2_PLR3_df, values = matrix.unlist.R2_PLR3...nrow...length.R2_PLR3...byrow...TRUE.)

#Calculate mean, max, min, sd and CIs of R2
R2_summary3 <- sapply(R2_PLR3_df, function(R2_PLR3_df) c( "min" = min(R2_PLR3_df), 
                                                            "max"= max(R2_PLR3_df),
                                                            "mean" = mean(R2_PLR3_df),
                                                            "sd_tree" = sd(R2_PLR3_df)))

Mean_ci_R2 <- mean_ci(R2_PLR3_df$values)
Mean_ci_R2 <- rename(Mean_ci_R2, mean = y)
Mean_ci_R2 <- rename(Mean_ci_R2, CI_low = ymin)
Mean_ci_R2 <- rename(Mean_ci_R2, CI_high = ymax)
rownames(Mean_ci_R2)[rownames(Mean_ci_R2) == "1"] <- "values"
R2_summary3 <- t(R2_summary3)
R2_summary3 <- as.data.frame(R2_summary3)
R2_summary3 <- merge(R2_summary3,Mean_ci_R2,by="mean")
rownames(R2_summary3)[rownames(R2_summary3) == "1"] <- "R2_lik"

#transform list AICc in data frame
AICc_PLR3_df <- data.frame(matrix(unlist(AICc_PLR3), nrow=length(AICc_PLR3), byrow=TRUE))
AICc_PLR3_df <- rename(AICc_PLR3_df, values = matrix.unlist.AICc_PLR3...nrow...length.AICc_PLR3...byrow...TRUE.)

#Calculate mean, max, min, sd and CIs of AICc
AICc_summary3 <- sapply(AICc_PLR3_df, function(AICc_PLR3_df) c( "min" = min(AICc_PLR3_df), 
                                                                  "max"= max(AICc_PLR3_df),
                                                                  "mean" = mean(AICc_PLR3_df),
                                                                  "sd_tree" = sd(AICc_PLR3_df)))

Mean_ci_AICc <- mean_ci(AICc_PLR3_df$values)
Mean_ci_AICc <- rename(Mean_ci_AICc, mean = y)
Mean_ci_AICc <- rename(Mean_ci_AICc, CI_low = ymin)
Mean_ci_AICc <- rename(Mean_ci_AICc, CI_high = ymax)
rownames(Mean_ci_AICc)[rownames(Mean_ci_AICc) == "1"] <- "values"
AICc_summary3 <- t(AICc_summary3)
AICc_summary3 <- as.data.frame(AICc_summary3)
AICc_summary3 <- merge(AICc_summary3,Mean_ci_AICc,by="mean")
rownames(AICc_summary3)[rownames(AICc_summary3) == "1"] <- "AICc"

#Add R2 and AICc to the other summ stats
stats_PLR3 <- rbind(stats_PLR3, R2_summary3, AICc_summary3)
stats_PLR3 <- add_rownames(stats_PLR3, "VALUE")
stats_PLR3

#Convert in a table
gt_tbl3 <- gt(stats_PLR3)

gt_tbl3 <- gt_tbl3 %>% tab_header(
  title = "Model: P(threatened) ~ Magnitude of body mass change",
  subtitle = "n = 487; 100 DNA-only trees")

gt_tbl3

#Save the table
gtsave(gt_tbl3, "Table_Summ_stats_PLR_P(threatened)_vs_Magnitude_size_change_extant_species_DNA_only_trees.html")

#######################################################
# Fit model and calculate summary stats for Body mass #
#######################################################

PLR2_DNA_only <- tree_phyglm(Pr_threatened_bin ~ Body_mass_island_taxon, data = db, phy = trees_DNA_only, n.tree = 100)
summary(PLR2_DNA_only)
sensi_plot4 <- sensi_plot(PLR2_DNA_only, graphs = 3)
ggsave(sensi_plot4, filename = "PLR_P(threatened)_vs_Body_mass_extant_species_phylo_uncertainty_trees_DNA_only.pdf", width = 6, height = 6, device = cairo_pdf) 

#Extract summary stats in a table
stats_PLR4 <- PLR2_DNA_only$all.stats
stats_PLR4 <- stats_PLR4 %>% mutate_if(is.numeric, round, digits=3)
rownames(stats_PLR4)[rownames(stats_PLR4) == "optpar"] <- "alpha"

#Calculate R2_lik and AICc across 100 DNA-only trees
#Set up a list to store results
R2_PLR4 <- list(length = trees_DNA_only) 
AICc_PLR4 <- list(length = trees_DNA_only)

#Run the model fitting analysis on all trees, calculate for each one a R2.lik and AICc value and store the results in the list
for(i in 1:length(trees_DNA_only)) {
  currentTree <- trees_DNA_only[[i]]
  PLR_iterated <- phyloglm(Pr_threatened_bin ~ Body_mass_island_taxon, data = db, phy = currentTree, method = c("logistic_MPLE"), boot = 100)
  R2_PLR4[i] <- R2.lik(PLR_iterated)
  AICc_PLR4[i] <- AICc.phyloglm(PLR_iterated)
}

#transform list R2 in data frame
R2_PLR4_df <- data.frame(matrix(unlist(R2_PLR4), nrow=length(R2_PLR4), byrow=TRUE))
R2_PLR4_df <- rename(R2_PLR4_df, values = matrix.unlist.R2_PLR4...nrow...length.R2_PLR4...byrow...TRUE.)

#Calculate mean, max, min, sd and CIs of R2
R2_summary4 <- sapply(R2_PLR4_df, function(R2_PLR4_df) c( "min" = min(R2_PLR4_df), 
                                                            "max"= max(R2_PLR4_df),
                                                            "mean" = mean(R2_PLR4_df),
                                                            "sd_tree" = sd(R2_PLR4_df)))

Mean_ci_R2 <- mean_ci(R2_PLR4_df$values)
Mean_ci_R2 <- rename(Mean_ci_R2, mean = y)
Mean_ci_R2 <- rename(Mean_ci_R2, CI_low = ymin)
Mean_ci_R2 <- rename(Mean_ci_R2, CI_high = ymax)
rownames(Mean_ci_R2)[rownames(Mean_ci_R2) == "1"] <- "values"
R2_summary4 <- t(R2_summary4)
R2_summary4 <- as.data.frame(R2_summary4)
R2_summary4 <- merge(R2_summary4,Mean_ci_R2,by="mean")
rownames(R2_summary4)[rownames(R2_summary4) == "1"] <- "R2_lik"

#transform list AICc in data frame
AICc_PLR4_df <- data.frame(matrix(unlist(AICc_PLR4), nrow=length(AICc_PLR4), byrow=TRUE))
AICc_PLR4_df <- rename(AICc_PLR4_df, values = matrix.unlist.AICc_PLR4...nrow...length.AICc_PLR4...byrow...TRUE.)

#Calculate mean, max, min, sd and CIs of AICc
AICc_summary4 <- sapply(AICc_PLR4_df, function(AICc_PLR4_df) c( "min" = min(AICc_PLR4_df), 
                                                                  "max"= max(AICc_PLR4_df),
                                                                  "mean" = mean(AICc_PLR4_df),
                                                                  "sd_tree" = sd(AICc_PLR4_df)))

Mean_ci_AICc <- mean_ci(AICc_PLR4_df$values)
Mean_ci_AICc <- rename(Mean_ci_AICc, mean = y)
Mean_ci_AICc <- rename(Mean_ci_AICc, CI_low = ymin)
Mean_ci_AICc <- rename(Mean_ci_AICc, CI_high = ymax)
rownames(Mean_ci_AICc)[rownames(Mean_ci_AICc) == "1"] <- "values"
AICc_summary4 <- t(AICc_summary4)
AICc_summary4 <- as.data.frame(AICc_summary4)
AICc_summary4 <- merge(AICc_summary4,Mean_ci_AICc,by="mean")
rownames(AICc_summary4)[rownames(AICc_summary4) == "1"] <- "AICc"

#Add R2 and AICc to the other summ stats
stats_PLR4 <- rbind(stats_PLR4, R2_summary4, AICc_summary4)
stats_PLR4 <- add_rownames(stats_PLR4, "VALUE")
stats_PLR4

#Convert in a table
gt_tbl4 <- gt(stats_PLR4)

gt_tbl4 <- gt_tbl4 %>% tab_header(
  title = "Model: P(threatened) ~ Body mass",
  subtitle = "n = 487; 100 DNA-only trees")

gt_tbl4

#Save the table
gtsave(gt_tbl4, "Table_Summ_stats_PLR_P(threatened)_vs_Body_mass_extant_species_DNA_only_trees.html")

#End of script
