# clean environment
rm(list=ls())

##############################################################
# Load libraries                                          ####
##############################################################

library(dplyr)
library(sensiPhy)
library(rr2)
library(ggplot2)
library(forcats)
library(ape)
library(ggpubr)
library(gt)
library(Cairo)

##############################################################
# Load data                                               ####
##############################################################

db_fossil <- read.csv('Data/Fossil_mammals_species_PLRs.csv')
db_extant <- read.csv('Data/Extant_mammals_species_PLRs.csv')

#Combine extant and fossil datasets
db_fossil <- dplyr::select(db_fossil, -c("Notes", "Source"))
db_extant <- dplyr::select(db_extant, -c("Source_Body_mass_and_size_ratio", "Source_Ancestor_or_closest_mainland_relative","Notes"))
db_total <- rbind(db_fossil, db_extant)

#remove taxa with not available BM and size ratio
db_total <- filter(db_total, Body_mass_island_taxon != "") 
db_total <- filter(db_total, Size_ratio != "")
#remove taxa that experienced no substantial size change
db_total <- filter(db_total, Direction_body_size_change != "no_change")
#remove prehistoric extinctions
db_total <- filter(db_total, IUCN_Category != "EP")

#Create extinct vs extant column
db_total <- db_total %>%
  mutate(Pr_extinction = recode_factor(IUCN_Category,
                                       EX = "extinct",
                                       CR = "extant",
                                       EN = "extant",
                                       VU = "extant",
                                       NT = "extant",
                                       LC = "extant"))

#Reorder extinct vs extant column from low to high extinction risk
db_total <- db_total %>%
  mutate(Pr_extinction =
           fct_relevel(Pr_extinction,
                       "extant",
                       "extinct"))

#Create extant vs extinct column as a binary output 
#0 = extant; 1 = extinct
db_total <- db_total %>%
  mutate(Pr_extinction_bin = recode_factor(Pr_extinction,
                                    extant = 0L,
                                    extinct = 1L))

##################################################
# Read complete trees generated by TACT       ####
##################################################

trees_complete_TACT <-read.nexus('Results/TACT/100trees_outputs_TACT.trees')

# Assign rownames to dataset
rownames(db_total)=db_total$Latin_binomial 

#############################################################################
# Fit PLR (Ives & Garland, 2010) for 2 main single predictor models      ####
# and run sensitivity analysis accounting for phylogenetic uncertainty   ####
# across 100 complete trees generated by TACT                            ####
#############################################################################

###################################################################
# Fit model and calculate summary stats for Magnitude_size_change #
###################################################################

PLR1 <- tree_phyglm(Pr_extinction_bin ~ Magnitude_body_size_change, data = db_total, phy = trees_complete_TACT, n.tree = 100)
summary(PLR1)
sensi_plot1 <- sensi_plot(PLR1, graphs = 3)
ggsave(sensi_plot1, filename = "PLR_P(hist_extinct)_vs_Magnitude_body_size_change_fossil_species_phylo_uncertainty_complete_trees_TACT.pdf", path = "Results/PLRs", width = 6, height = 6, device = cairo_pdf)

#Extract summary stats in a table
stats_PLR1 <- PLR1$all.stats
stats_PLR1 <- stats_PLR1 %>% mutate_if(is.numeric, round, digits=3)
rownames(stats_PLR1)[rownames(stats_PLR1) == "optpar"] <- "alpha"

#Calculate R2_lik and AICc across 100 complete trees generated by TACT
#Set up a list to store results
R2_PLR1 <- list(length = trees_complete_TACT) 
AICc_PLR1 <- list(length = trees_complete_TACT)

#Function to calculate AICc (from https://github.com/mrhelmus/phylogeny_manipulation/blob/master/AIC_func.r)
AICc.phyloglm<-function(mod, return.K = FALSE, second.ord = TRUE, nobs = NULL, ...){
  
  if(identical(nobs, NULL)) {n <- length(mod$residuals)} else {n <- nobs}
  LL <- logLik(mod)$logLik
  K <- logLik(mod)$df  #extract correct number of parameters included in model - this includes LM
  if(second.ord == TRUE) {AICc <- -2*LL+2*K*(n/(n-K-1))}  else{AICc <- -2*LL+2*K}
  if(return.K == TRUE) AICc[1] <- K #attributes the first element of AICc to K
  return(AICc)
}


#Run the model fitting analysis on all trees, calculate for each one a R2.lik and AICc value and store the results in the list
for(i in 1:length(trees_complete_TACT)) {
  currentTree <- trees_complete_TACT[[i]]
  PLR_iterated <- phyloglm(Pr_extinction_bin ~ Magnitude_body_size_change, data = db_total, phy = currentTree, method = c("logistic_MPLE"), boot = 100)
  R2_PLR1[i] <- R2_lik(PLR_iterated)
  AICc_PLR1[i] <- AICc.phyloglm(PLR_iterated)
}

#transform list R2 in data frame
R2_PLR1_df <- data.frame(matrix(unlist(R2_PLR1), nrow=length(R2_PLR1), byrow=TRUE))
R2_PLR1_df <- rename(R2_PLR1_df, values = matrix.unlist.R2_PLR1...nrow...length.R2_PLR1...byrow...TRUE.)

#Calculate mean, max, min, sd and CIs of R2
R2_summary1 <- sapply(R2_PLR1_df, function(R2_PLR1_df) c( "min" = min(R2_PLR1_df), 
                                                            "max"= max(R2_PLR1_df),
                                                            "mean" = mean(R2_PLR1_df),
                                                            "sd_tree" = sd(R2_PLR1_df)))

Mean_ci_R2 <- mean_ci(R2_PLR1_df$values)
Mean_ci_R2 <- rename(Mean_ci_R2, mean = y)
Mean_ci_R2 <- rename(Mean_ci_R2, CI_low = ymin)
Mean_ci_R2 <- rename(Mean_ci_R2, CI_high = ymax)
rownames(Mean_ci_R2)[rownames(Mean_ci_R2) == "1"] <- "values"
R2_summary1 <- t(R2_summary1)
R2_summary1 <- as.data.frame(R2_summary1)
R2_summary1 <- merge(R2_summary1,Mean_ci_R2,by="mean")
rownames(R2_summary1)[rownames(R2_summary1) == "1"] <- "R2_lik"

#transform list AICc in data frame
AICc_PLR1_df <- data.frame(matrix(unlist(AICc_PLR1), nrow=length(AICc_PLR1), byrow=TRUE))
AICc_PLR1_df <- rename(AICc_PLR1_df, values = matrix.unlist.AICc_PLR1...nrow...length.AICc_PLR1...byrow...TRUE.)

#Calculate mean, max, min, sd and CIs of AICc
AICc_summary1 <- sapply(AICc_PLR1_df, function(AICc_PLR1_df) c( "min" = min(AICc_PLR1_df), 
                                                                  "max"= max(AICc_PLR1_df),
                                                                  "mean" = mean(AICc_PLR1_df),
                                                                  "sd_tree" = sd(AICc_PLR1_df)))

Mean_ci_AICc <- mean_ci(AICc_PLR1_df$values)
Mean_ci_AICc <- rename(Mean_ci_AICc, mean = y)
Mean_ci_AICc <- rename(Mean_ci_AICc, CI_low = ymin)
Mean_ci_AICc <- rename(Mean_ci_AICc, CI_high = ymax)
rownames(Mean_ci_AICc)[rownames(Mean_ci_AICc) == "1"] <- "values"
AICc_summary1 <- t(AICc_summary1)
AICc_summary1 <- as.data.frame(AICc_summary1)
AICc_summary1 <- merge(AICc_summary1,Mean_ci_AICc,by="mean")
rownames(AICc_summary1)[rownames(AICc_summary1) == "1"] <- "AICc"

#Add R2 and AICc to the other summ stats
stats_PLR1 <- rbind(stats_PLR1, R2_summary1, AICc_summary1)
stats_PLR1
stats_PLR1 <- add_rownames(stats_PLR1, "VALUE")
stats_PLR1

#Convert in a table
gt_tbl1 <- gt(stats_PLR1)

gt_tbl1 <- gt_tbl1 %>% tab_header(
  title = "Model: P(hist_extinct) ~ Magnitude of body mass change",
  subtitle = "n = 668; 100 complete TACT trees")

gt_tbl1

#Save the table
gtsave(gt_tbl1, filename = "Table_Summ_stats_PLR_P(hist_extinct)_vs_Magnitude_fossil_species.html", path = "Results/PLRs")

#######################################################
# Fit model and calculate summary stats for Body mass #
#######################################################

db_total$Body_mass_island_taxon <- scale(db_total$Body_mass_island_taxon) #scale BM
PLR2 <- tree_phyglm(Pr_extinction_bin ~ Body_mass_island_taxon, data = db_total, phy = trees_complete_TACT, n.tree = 100, btol = 25)
summary(PLR2)
sensi_plot2 <- sensi_plot(PLR2, graphs = 3)
ggsave(sensi_plot2, filename = "PLR_P(hist_extinct)_vs_Body_mass_fossil_species_phylo_uncertainty_complete_trees_TACT.pdf", path = "Results/PLRs", width = 6, height = 6, device = cairo_pdf)

#Extract summary stats in a table
stats_PLR2 <- PLR2$all.stats
stats_PLR2 <- stats_PLR2 %>% mutate_if(is.numeric, round, digits=3)
rownames(stats_PLR2)[rownames(stats_PLR2) == "optpar"] <- "alpha"

#Calculate R2_lik and AICc across 100 complete trees generated by TACT
#Set up a list to store results
R2_PLR2 <- list(length = trees_complete_TACT) 
AICc_PLR2 <- list(length = trees_complete_TACT)

#Run the model fitting analysis on all trees, calculate for each one a R2.lik and AICc value and store the results in the list
for(i in 1:length(trees_complete_TACT)) {
  currentTree <- trees_complete_TACT[[i]]
  PLR_iterated <- phyloglm(Pr_extinction_bin ~ Body_mass_island_taxon, data = db_total, phy = currentTree, method = c("logistic_MPLE"), boot = 100)
  R2_PLR2[i] <- R2_lik(PLR_iterated)
  AICc_PLR2[i] <- AICc.phyloglm(PLR_iterated)
}

#transform list in data frame
R2_PLR2_df <- data.frame(matrix(unlist(R2_PLR2), nrow=length(R2_PLR2), byrow=TRUE))
R2_PLR2_df <- rename(R2_PLR2_df, values = matrix.unlist.R2_PLR2...nrow...length.R2_PLR2...byrow...TRUE.)

#Calculate mean, max, min, sd and CIs of R2
R2_summary2 <- sapply(R2_PLR2_df, function(R2_PLR2_df) c( "min" = min(R2_PLR2_df), 
                                                            "max"= max(R2_PLR2_df),
                                                            "mean" = mean(R2_PLR2_df),
                                                            "sd_tree" = sd(R2_PLR2_df)))

Mean_ci_R2 <- mean_ci(R2_PLR2_df$values)
Mean_ci_R2 <- rename(Mean_ci_R2, mean = y)
Mean_ci_R2 <- rename(Mean_ci_R2, CI_low = ymin)
Mean_ci_R2 <- rename(Mean_ci_R2, CI_high = ymax)
rownames(Mean_ci_R2)[rownames(Mean_ci_R2) == "1"] <- "values"
R2_summary2 <- t(R2_summary2)
R2_summary2 <- as.data.frame(R2_summary2)
R2_summary2 <- merge(R2_summary2,Mean_ci_R2,by="mean")
rownames(R2_summary2)[rownames(R2_summary2) == "1"] <- "R2_lik"

#transform list in data frame
AICc_PLR2_df <- data.frame(matrix(unlist(AICc_PLR2), nrow=length(AICc_PLR2), byrow=TRUE))
AICc_PLR2_df <- rename(AICc_PLR2_df, values = matrix.unlist.AICc_PLR2...nrow...length.AICc_PLR2...byrow...TRUE.)

#Calculate mean, max, min, sd and CIs of AICc
AICc_summary2 <- sapply(AICc_PLR2_df, function(AICc_PLR2_df) c( "min" = min(AICc_PLR2_df), 
                                                                  "max"= max(AICc_PLR2_df),
                                                                  "mean" = mean(AICc_PLR2_df),
                                                                  "sd_tree" = sd(AICc_PLR2_df)))

Mean_ci_AICc <- mean_ci(AICc_PLR2_df$values)
Mean_ci_AICc <- rename(Mean_ci_AICc, mean = y)
Mean_ci_AICc <- rename(Mean_ci_AICc, CI_low = ymin)
Mean_ci_AICc <- rename(Mean_ci_AICc, CI_high = ymax)
rownames(Mean_ci_AICc)[rownames(Mean_ci_AICc) == "1"] <- "values"
AICc_summary2 <- t(AICc_summary2)
AICc_summary2 <- as.data.frame(AICc_summary2)
AICc_summary2 <- merge(AICc_summary2,Mean_ci_AICc,by="mean")
rownames(AICc_summary2)[rownames(AICc_summary2) == "1"] <- "AICc"

#Add R2 and AICc to the other summ stats 
stats_PLR2 <- rbind(stats_PLR2, R2_summary2, AICc_summary2)
stats_PLR2
stats_PLR2 <- add_rownames(stats_PLR2, "VALUE")
stats_PLR2

#Convert in a table
gt_tbl2 <- gt(stats_PLR2)

gt_tbl2 <- gt_tbl2 %>% tab_header(
  title = "Model: P(hist_extinct) ~ Body mass",
  subtitle = "n = 668; 100 complete TACT trees")

gt_tbl2

#Save the table
gtsave(gt_tbl2, filename = "Table_Summ_stats_PLR_P(hist_extinct)_vs_Body_mass_fossil_species.html", path = "Results/PLRs")

#End of script
