# clean environment
rm(list=ls())

##############################################################
# Load libraries                                          ####
##############################################################

library(dplyr)
library(sensiPhy)
library(rr2)
library(ggplot2)
library(forcats)
library(ape)
library(ggpubr)
library(gt)
library(Cairo)

##############################################################
# Load data                                               ####
##############################################################

db <- read.csv('Data/Extant_mammals_populations_PLRs.csv')

#remove taxa with not available BM
db <- filter(db, Body_mass_island_taxon != "") 
#remove taxa that experienced no substantial size change
db <- filter(db, Direction_body_size_change != "no_change")

#Create threatened vs nonthreatened column
db <- db %>%
  mutate(Pr_threatened = recode_factor(IUCN_Category,
                                CR = "threatened",
                                EN = "threatened",
                                VU = "threatened",
                                NT = "nonthreatened",
                                LC = "nonthreatened"))

#Reorder threatened vs nonthreatened column from low to high extinction risk
db <- db %>%
  mutate(Pr_threatened =
           fct_relevel(Pr_threatened,
                       "nonthreatened",
                       "threatened"))

#Create threatened vs nonthreatened column as a binary output 
#0 = nonthreatened; 1 = threatened
db <- db %>%
  mutate(Pr_threatened_bin = recode(Pr_threatened,
                                    nonthreatened = 0L,
                                    threatened = 1L))


#########################################################
# Read trees: complete trees generated by TACT and   ####
# DNA-only trees                                     ####
#########################################################

trees_complete <- read.nexus('Results/TACT/100trees_outputs_TACT.trees')

trees_DNA_only <- read.nexus('Results/TACT/100_trees_DNA_only.trees')

#Create data frame with mean and dev st for Magnitude_body_size_change and BM

db$Body_mass_island_taxon_scaled <- scale(db$Body_mass_island_taxon) #scale BM
db1_intra <- group_by(db, Latin_binomial) %>% summarize(Magnitude_body_size_change_mean = mean(Magnitude_body_size_change))
db2_intra <- group_by(db, Latin_binomial) %>% summarize(Body_mass_island_taxon_scaled_mean = mean(Body_mass_island_taxon_scaled))
db3_intra <- group_by(db, Latin_binomial) %>% summarize(Magnitude_body_size_change_sd = sd(Magnitude_body_size_change))
db4_intra <- group_by(db, Latin_binomial) %>% summarize(Body_mass_island_taxon_scaled_sd = sd(Body_mass_island_taxon_scaled))
db5_intra <- group_by(db, Latin_binomial) %>% summarize(Size_ratio_mean = mean(Size_ratio))
db6_intra <- left_join(db1_intra, db2_intra, by = "Latin_binomial")
db7_intra <- left_join(db3_intra, db4_intra, by = "Latin_binomial")
db8_intra <- left_join(db6_intra, db7_intra, by = "Latin_binomial")
db9_intra <- left_join(db8_intra, db5_intra, by = "Latin_binomial")
db_intra <- left_join(db9_intra, db, by = "Latin_binomial")
db_intra <- filter(db_intra, Size_ratio_mean != "1") #remove observation with mean size ratio = 1

#Create direction size change column from mean values Size ratio

db_intra <- db_intra %>%
  mutate(Direction_body_size_change_mean = if_else(Size_ratio_mean > 1, "gigantism", "dwarfism"))
db_intra <- dplyr::select(db_intra, Latin_binomial, Body_mass_island_taxon_scaled_mean, Body_mass_island_taxon_scaled_sd, Magnitude_body_size_change_mean, Magnitude_body_size_change_sd, Direction_body_size_change_mean, IUCN_Category, Pr_threatened_bin)

#Remove duplicates
db_intra <- unique(db_intra)
db_intra <- as.data.frame(db_intra) 
db_intra$Latin_binomial # Get the column called 'Latin.binomial' as a vector

#Assign rownames to dataset
rownames(db_intra) = db_intra$Latin_binomial

#############################################################################
# Fit PLR (Ives & Garland, 2010) for 2 main single predictor models      ####
# and run sensitivity analysis accounting for phylogenetic uncertainty   ####
# across 100 complete trees generated by TACT and intraspecific          ####
# variation                                                              ####
#############################################################################

###################################################################
# Fit model and calculate summary stats for Magnitude_size_change #
###################################################################

PLR5 <- tree_intra_phyglm(Pr_threatened_bin ~ Magnitude_body_size_change_mean, data = db_intra, phy = trees_complete, Vx = "Magnitude_body_size_change_sd", n.intra = 30, n.tree = 100)
#Summary results:
summary(PLR5)
#Visualize diagnostics for interaction between phylo uncertainty and data uncertainty
sensi_plot5 <- sensi_plot(PLR5, graphs = 3, uncer.type = "all")
ggsave(sensi_plot5, filename = "PLR_P(threatened)_vs_Magnitude_body_size_change_phylo_intra_uncertainty_extant_pops_complete_trees_TACT.pdf", path = "Results/PLRs", width = 6, height = 6, device = cairo_pdf)

#Extract summary stats in a table
stats_PLR5 <- PLR5$all.stats
stats_PLR5 <- stats_PLR5 %>% mutate_if(is.numeric, round, digits=3)
rownames(stats_PLR5)[rownames(stats_PLR5) == "optpar"] <- "alpha"
stats_PLR5

#Calculate R2_lik and AICc across 100 complete trees generated by TACT
#Set up a list to store results
R2_PLR5 <- list(length = trees_complete) 
AICc_PLR5 <- list(length = trees_complete) 

#Function to calculate AICc (from https://github.com/mrhelmus/phylogeny_manipulation/blob/master/AIC_func.r)
AICc.phyloglm<-function(mod, return.K = FALSE, second.ord = TRUE, nobs = NULL, ...){
  
  if(identical(nobs, NULL)) {n <- length(mod$residuals)} else {n <- nobs}
  LL <- logLik(mod)$logLik
  K <- logLik(mod)$df  #extract correct number of parameters included in model - this includes LM
  if(second.ord == TRUE) {AICc <- -2*LL+2*K*(n/(n-K-1))}  else{AICc <- -2*LL+2*K}
  if(return.K == TRUE) AICc[1] <- K #attributes the first element of AICc to K
  return(AICc)
}

#Run the model fitting analysis on all trees, calculate for each one a R2.lik and AICc value and store the results in the list
for(i in 1:length(trees_complete)) {
  currentTree <- trees_complete[[i]]
  PLR_iterated <- phyloglm(Pr_threatened_bin ~ Magnitude_body_size_change_mean, data = db_intra, phy = currentTree, method = c("logistic_MPLE"), boot = 100)
  R2_PLR5[i] <- R2_lik(PLR_iterated)
  AICc_PLR5[i] <- AICc.phyloglm(PLR_iterated)
}

#transform list R2 in data frame
R2_PLR5_df <- data.frame(matrix(unlist(R2_PLR5), nrow=length(R2_PLR5), byrow=TRUE))
R2_PLR5_df <- rename(R2_PLR5_df, values = matrix.unlist.R2_PLR5...nrow...length.R2_PLR5...byrow...TRUE.)

#Calculate mean, max, min, sd and CIs of R2
R2_summary5 <- sapply(R2_PLR5_df, function(R2_PLR5_df) c( "min" = min(R2_PLR5_df), 
                                                            "max"= max(R2_PLR5_df),
                                                            "mean" = mean(R2_PLR5_df),
                                                            "sd_tree" = sd(R2_PLR5_df)))

Mean_ci_R2 <- mean_ci(R2_PLR5_df$values)
Mean_ci_R2 <- rename(Mean_ci_R2, mean = y)
Mean_ci_R2 <- rename(Mean_ci_R2, CI_low = ymin)
Mean_ci_R2 <- rename(Mean_ci_R2, CI_high = ymax)
rownames(Mean_ci_R2)[rownames(Mean_ci_R2) == "1"] <- "values"
R2_summary5 <- t(R2_summary5)
R2_summary5 <- as.data.frame(R2_summary5)
R2_summary5 <- merge(R2_summary5,Mean_ci_R2,by="mean")
rownames(R2_summary5)[rownames(R2_summary5) == "1"] <- "R2_lik"

#transform list AICc in data frame
AICc_PLR5_df <- data.frame(matrix(unlist(AICc_PLR5), nrow=length(AICc_PLR5), byrow=TRUE))
AICc_PLR5_df <- rename(AICc_PLR5_df, values = matrix.unlist.AICc_PLR5...nrow...length.AICc_PLR5...byrow...TRUE.)

#Calculate mean, max, min, sd and CIs of AICc
AICc_summary5 <- sapply(AICc_PLR5_df, function(AICc_PLR5_df) c( "min" = min(AICc_PLR5_df), 
                                                                  "max"= max(AICc_PLR5_df),
                                                                  "mean" = mean(AICc_PLR5_df),
                                                                  "sd_tree" = sd(AICc_PLR5_df)))

Mean_ci_AICc <- mean_ci(AICc_PLR5_df$values)
Mean_ci_AICc <- rename(Mean_ci_AICc, mean = y)
Mean_ci_AICc <- rename(Mean_ci_AICc, CI_low = ymin)
Mean_ci_AICc <- rename(Mean_ci_AICc, CI_high = ymax)
rownames(Mean_ci_AICc)[rownames(Mean_ci_AICc) == "1"] <- "values"
AICc_summary5 <- t(AICc_summary5)
AICc_summary5 <- as.data.frame(AICc_summary5)
AICc_summary5 <- merge(AICc_summary5,Mean_ci_AICc,by="mean")
rownames(AICc_summary5)[rownames(AICc_summary5) == "1"] <- "AICc"

#Add R2 and AICc to the other summ stats 
R2_summary5 <- rename(R2_summary5, mean.tree = mean)
R2_summary5 <- rename(R2_summary5, max.tree = max)
R2_summary5 <- rename(R2_summary5, min.tree = min)
R2_summary5 <- rename(R2_summary5, CI_low_tree = CI_low)
R2_summary5 <- rename(R2_summary5, CI_high_tree = CI_high)
AICc_summary5 <- rename(AICc_summary5, mean.tree = mean)
AICc_summary5 <- rename(AICc_summary5, max.tree = max)
AICc_summary5 <- rename(AICc_summary5, min.tree = min)
AICc_summary5 <- rename(AICc_summary5, CI_low_tree = CI_low)
AICc_summary5 <- rename(AICc_summary5, CI_high_tree = CI_high)

stats_PLR5 <- bind_rows(stats_PLR5, R2_summary5, AICc_summary5)
stats_PLR5

stats_PLR5 <- add_rownames(stats_PLR5, "VALUE")

#Convert in a table
gt_tbl5 <- gt(stats_PLR5)

gt_tbl5 <- gt_tbl5 %>% tab_header(
  title = "Model: P(threatened) ~ Magnitude of body mass change",
  subtitle = "n_species = 384; 100 complete TACT trees")

gt_tbl5

#Save the table
gtsave(gt_tbl5, filename = "Table_Summ_stats_PLR_P(threatened)_vs_Magnitude_phylo_intra_uncertainty_extant_pops_complete_trees_TACT.html", path = "Results/PLRs")

#######################################################
# Fit model and calculate summary stats for Body mass #
#######################################################

PLR6 <- tree_intra_phyglm(Pr_threatened_bin ~ Body_mass_island_taxon_scaled_mean, data = db_intra, phy = trees_complete, Vx = "Body_mass_island_taxon_scaled_sd", n.intra = 30, n.tree = 100)
#Summary results:
summary(PLR6)
#Visualize diagnostics for interaction between phylo uncertainty and data uncertainty
sensi_plot6 <- sensi_plot(PLR6, graphs = 3, uncer.type = "all")
ggsave(sensi_plot6, filename = "PLR_P(threatened)_vs_Body_mass_phylo_intra_uncertainty_extant_pops_complete_trees_TACT.pdf", path = "Results/PLRs", width = 6, height = 6, device = cairo_pdf) 

#Extract summary stats in a table
stats_PLR6 <- PLR6$all.stats
stats_PLR6 <- stats_PLR6 %>% mutate_if(is.numeric, round, digits=3)
rownames(stats_PLR6)[rownames(stats_PLR6) == "optpar"] <- "alpha"
stats_PLR6

#Calculate R2_lik and AICc across 100 complete trees generated by TACT
#Set up a list to store results
R2_PLR6 <- list(length = trees_complete) 
AICc_PLR6 <- list(length = trees_complete) 

#Run the model fitting analysis on all trees, calculate for each one a R2.lik and AICc value and store the results in the list
for(i in 1:length(trees_complete)) {
  currentTree <- trees_complete[[i]]
  PLR_iterated <- phyloglm(Pr_threatened_bin ~ Body_mass_island_taxon_scaled_mean, data = db_intra, phy = currentTree, method = c("logistic_MPLE"), boot = 100)
  R2_PLR6[i] <- R2_lik(PLR_iterated)
  AICc_PLR6[i] <- AICc.phyloglm(PLR_iterated)
}

#transform list R2 in data frame
R2_PLR6_df <- data.frame(matrix(unlist(R2_PLR6), nrow=length(R2_PLR6), byrow=TRUE))
R2_PLR6_df <- rename(R2_PLR6_df, values = matrix.unlist.R2_PLR6...nrow...length.R2_PLR6...byrow...TRUE.)

#Calculate mean, max, min, sd and CIs of R2
R2_summary6 <- sapply(R2_PLR6_df, function(R2_PLR6_df) c( "min" = min(R2_PLR6_df), 
                                                            "max"= max(R2_PLR6_df),
                                                            "mean" = mean(R2_PLR6_df),
                                                            "sd_tree" = sd(R2_PLR6_df)))

Mean_ci_R2 <- mean_ci(R2_PLR6_df$values)
Mean_ci_R2 <- rename(Mean_ci_R2, mean = y)
Mean_ci_R2 <- rename(Mean_ci_R2, CI_low = ymin)
Mean_ci_R2 <- rename(Mean_ci_R2, CI_high = ymax)
rownames(Mean_ci_R2)[rownames(Mean_ci_R2) == "1"] <- "values"
R2_summary6 <- t(R2_summary6)
R2_summary6 <- as.data.frame(R2_summary6)
R2_summary6 <- merge(R2_summary6,Mean_ci_R2,by="mean")
rownames(R2_summary6)[rownames(R2_summary6) == "1"] <- "R2_lik"

#transform list AICc in data frame
AICc_PLR6_df <- data.frame(matrix(unlist(AICc_PLR6), nrow=length(AICc_PLR6), byrow=TRUE))
AICc_PLR6_df <- rename(AICc_PLR6_df, values = matrix.unlist.AICc_PLR6...nrow...length.AICc_PLR6...byrow...TRUE.)

#Calculate mean, max, min, sd and CIs of AICc
AICc_summary6 <- sapply(AICc_PLR6_df, function(AICc_PLR6_df) c( "min" = min(AICc_PLR6_df), 
                                                                  "max"= max(AICc_PLR6_df),
                                                                  "mean" = mean(AICc_PLR6_df),
                                                                  "sd_tree" = sd(AICc_PLR6_df)))

Mean_ci_AICc <- mean_ci(AICc_PLR6_df$values)
Mean_ci_AICc <- rename(Mean_ci_AICc, mean = y)
Mean_ci_AICc <- rename(Mean_ci_AICc, CI_low = ymin)
Mean_ci_AICc <- rename(Mean_ci_AICc, CI_high = ymax)
rownames(Mean_ci_AICc)[rownames(Mean_ci_AICc) == "1"] <- "values"
AICc_summary6 <- t(AICc_summary6)
AICc_summary6 <- as.data.frame(AICc_summary6)
AICc_summary6 <- merge(AICc_summary6,Mean_ci_AICc,by="mean")
rownames(AICc_summary6)[rownames(AICc_summary6) == "1"] <- "AICc"

#Add R2 and AICc to the other summ stats 
R2_summary6 <- rename(R2_summary6, mean.tree = mean)
R2_summary6 <- rename(R2_summary6, max.tree = max)
R2_summary6 <- rename(R2_summary6, min.tree = min)
R2_summary6 <- rename(R2_summary6, CI_low_tree = CI_low)
R2_summary6 <- rename(R2_summary6, CI_high_tree = CI_high)
AICc_summary6 <- rename(AICc_summary6, mean.tree = mean)
AICc_summary6 <- rename(AICc_summary6, max.tree = max)
AICc_summary6 <- rename(AICc_summary6, min.tree = min)
AICc_summary6 <- rename(AICc_summary6, CI_low_tree = CI_low)
AICc_summary6 <- rename(AICc_summary6, CI_high_tree = CI_high)

stats_PLR6 <- bind_rows(stats_PLR6, R2_summary6, AICc_summary6)
stats_PLR6 <- add_rownames(stats_PLR6, "VALUE")
stats_PLR6

#Convert in a table
gt_tbl6 <- gt(stats_PLR6)

gt_tbl6 <- gt_tbl6 %>% tab_header(
  title = "Model: P(threatened) ~ Body mass",
  subtitle = "n_species = 384; 100 complete TACT trees")

gt_tbl6

#Save the table
gtsave(gt_tbl6, filename = "Table_Summ_stats_PLR_P(threatened)_vs_Body_mass_phylo_intra_uncertainty_extant_pops_complete_trees_TACT.html", path = "Results/PLRs")

#############################################################################
# Fit PLR (Ives & Garland, 2010) for 2 main single predictor models      ####
# and run sensitivity analysis accounting for phylogenetic uncertainty   ####
# across 100 DNA-only trees and intraspecific variation                  ####
#############################################################################

###################################################################
# Fit model and calculate summary stats for Magnitude_size_change #
###################################################################

PLR7 <- tree_intra_phyglm(Pr_threatened_bin ~ Magnitude_body_size_change_mean, data = db_intra, phy = trees_DNA_only, Vx = "Magnitude_body_size_change_sd", n.intra = 30, n.tree = 100)
#Summary results:
summary(PLR7)
#Visualize diagnostics for interaction between phylo uncertainty and data uncertainty
sensi_plot7 <- sensi_plot(PLR7, graphs = 3, uncer.type = "all") 
ggsave(sensi_plot7, filename = "PLR_P(threatened)_vs_Magnitude_body_size_change_phylo_intra_uncertainty_extant_pops_trees_DNA_only.pdf", path = "Results/PLRs", width = 6, height = 6, device = cairo_pdf) 

#Extract summary stats in a table
stats_PLR7 <- PLR7$all.stats
stats_PLR7 <- stats_PLR7 %>% mutate_if(is.numeric, round, digits=3)
rownames(stats_PLR7)[rownames(stats_PLR7) == "optpar"] <- "alpha"

#Calculate R2_lik and AICc across 100 DNA-only trees
#Set up a list to store results
R2_PLR7 <- list(length = trees_DNA_only) 
AICc_PLR7 <- list(length = trees_DNA_only) 

#Run the model fitting analysis on all trees, calculate for each one a R2.lik and AICc value and store the results in the list
for(i in 1:length(trees_DNA_only)) {
  currentTree <- trees_DNA_only[[i]]
  PLR_iterated <- phyloglm(Pr_threatened_bin ~ Magnitude_body_size_change_mean, data = db_intra, phy = currentTree, method = c("logistic_MPLE"), boot = 100)
  R2_PLR7[i] <- R2_lik(PLR_iterated)
  AICc_PLR7[i] <- AICc.phyloglm(PLR_iterated)
}

#transform list R2 in data frame
R2_PLR7_df <- data.frame(matrix(unlist(R2_PLR7), nrow=length(R2_PLR7), byrow=TRUE))
R2_PLR7_df <- rename(R2_PLR7_df, values = matrix.unlist.R2_PLR7...nrow...length.R2_PLR7...byrow...TRUE.)

#Calculate mean, max, min, sd and CIs of R2
R2_summary7 <- sapply(R2_PLR7_df, function(R2_PLR7_df) c( "min" = min(R2_PLR7_df), 
                                                            "max"= max(R2_PLR7_df),
                                                            "mean" = mean(R2_PLR7_df),
                                                            "sd_tree" = sd(R2_PLR7_df)))

Mean_ci_R2 <- mean_ci(R2_PLR7_df$values)
Mean_ci_R2 <- rename(Mean_ci_R2, mean = y)
Mean_ci_R2 <- rename(Mean_ci_R2, CI_low = ymin)
Mean_ci_R2 <- rename(Mean_ci_R2, CI_high = ymax)
rownames(Mean_ci_R2)[rownames(Mean_ci_R2) == "1"] <- "values"
R2_summary7 <- t(R2_summary7)
R2_summary7 <- as.data.frame(R2_summary7)
R2_summary7 <- merge(R2_summary7,Mean_ci_R2,by="mean")
rownames(R2_summary7)[rownames(R2_summary7) == "1"] <- "R2_lik"

#transform list AICc in data frame
AICc_PLR7_df <- data.frame(matrix(unlist(AICc_PLR7), nrow=length(AICc_PLR7), byrow=TRUE))
AICc_PLR7_df <- rename(AICc_PLR7_df, values = matrix.unlist.AICc_PLR7...nrow...length.AICc_PLR7...byrow...TRUE.)

#Calculate mean, max, min, sd and CIs of AICc
AICc_summary7 <- sapply(AICc_PLR7_df, function(AICc_PLR7_df) c( "min" = min(AICc_PLR7_df), 
                                                                  "max"= max(AICc_PLR7_df),
                                                                  "mean" = mean(AICc_PLR7_df),
                                                                  "sd_tree" = sd(AICc_PLR7_df)))

Mean_ci_AICc <- mean_ci(AICc_PLR7_df$values)
Mean_ci_AICc <- rename(Mean_ci_AICc, mean = y)
Mean_ci_AICc <- rename(Mean_ci_AICc, CI_low = ymin)
Mean_ci_AICc <- rename(Mean_ci_AICc, CI_high = ymax)
rownames(Mean_ci_AICc)[rownames(Mean_ci_AICc) == "1"] <- "values"
AICc_summary7 <- t(AICc_summary7)
AICc_summary7 <- as.data.frame(AICc_summary7)
AICc_summary7 <- merge(AICc_summary7,Mean_ci_AICc,by="mean")
rownames(AICc_summary7)[rownames(AICc_summary7) == "1"] <- "AICc"

#Add R2 and AICc to the other summ stats 
R2_summary7 <- rename(R2_summary7, mean.tree = mean)
R2_summary7 <- rename(R2_summary7, max.tree = max)
R2_summary7 <- rename(R2_summary7, min.tree = min)
R2_summary7 <- rename(R2_summary7, CI_low_tree = CI_low)
R2_summary7 <- rename(R2_summary7, CI_high_tree = CI_high)
AICc_summary7 <- rename(AICc_summary7, mean.tree = mean)
AICc_summary7 <- rename(AICc_summary7, max.tree = max)
AICc_summary7 <- rename(AICc_summary7, min.tree = min)
AICc_summary7 <- rename(AICc_summary7, CI_low_tree = CI_low)
AICc_summary7 <- rename(AICc_summary7, CI_high_tree = CI_high)

stats_PLR7 <- bind_rows(stats_PLR7, R2_summary7, AICc_summary7)
stats_PLR5
stats_PLR7 <- add_rownames(stats_PLR7, "VALUE")
stats_PLR7

#Convert in a table
gt_tbl7 <- gt(stats_PLR7)

gt_tbl7 <- gt_tbl7 %>% tab_header(
  title = "Model: P(threatened) ~ Magnitude of body mass change",
  subtitle = "n_species = 331; 100 DNA-only trees")

gt_tbl7

#Save the table
gtsave(gt_tbl7, filename = "Table_Summ_stats_PLR_P(threatened)_vs_Magnitude_phylo_intra_uncertainty_extant_pops_DNA_only_trees.html", path = "Results/PLRs")

#######################################################
# Fit model and calculate summary stats for Body mass #
#######################################################

PLR8 <- tree_intra_phyglm(Pr_threatened_bin ~ Body_mass_island_taxon_scaled_mean, data = db_intra, phy = trees_DNA_only, Vx = "Body_mass_island_taxon_scaled_sd", n.intra = 30, n.tree = 100)
#Summary results:
summary(PLR8)
#Visualize diagnostics for interaction between phylo uncertainty and data uncertainty
sensi_plot8 <- sensi_plot(PLR8, graphs = 3, uncer.type = "all") 
ggsave(sensi_plot8, filename = "PLR_P(threatened)_vs_Body_mass_phylo_intra_uncertainty_extant_pops_trees_DNA_only.pdf", path = "Results/PLRs", width = 6, height = 6, device = cairo_pdf) 

#Extract summary stats in a table
stats_PLR8 <- PLR8$all.stats
stats_PLR8 <- stats_PLR8 %>% mutate_if(is.numeric, round, digits=8)
rownames(stats_PLR8)[rownames(stats_PLR8) == "optpar"] <- "alpha"

#Calculate R2_lik and AICc across 100 DNA-only trees
#Set up a list to store results

R2_PLR8 <- list(length = trees_DNA_only) 
AICc_PLR8 <- list(length = trees_DNA_only) 

#Run the model fitting analysis on all trees, calculate for each one a R2.lik and AICc value and store the results in the list
for(i in 1:length(trees_DNA_only)) {
  currentTree <- trees_DNA_only[[i]]
  PLR_iterated <- phyloglm(Pr_threatened_bin ~ Body_mass_island_taxon_scaled_mean, data = db_intra, phy = currentTree, method = c("logistic_MPLE"), boot = 100)
  R2_PLR8[i] <- R2_lik(PLR_iterated)
  AICc_PLR8[i] <- AICc.phyloglm(PLR_iterated)
}

#transform list R2 in data frame
R2_PLR8_df <- data.frame(matrix(unlist(R2_PLR8), nrow=length(R2_PLR8), byrow=TRUE))

R2_PLR8_df <- rename(R2_PLR8_df, values = matrix.unlist.R2_PLR8...nrow...length.R2_PLR8...byrow...TRUE.)

#Calculate mean, max, min, sd and CIs of R2
R2_summary8 <- sapply(R2_PLR8_df, function(R2_PLR8_df) c( "min" = min(R2_PLR8_df), 
                                                            "max"= max(R2_PLR8_df),
                                                            "mean" = mean(R2_PLR8_df),
                                                            "sd_tree" = sd(R2_PLR8_df)))

Mean_ci_R2 <- mean_ci(R2_PLR8_df$values)
Mean_ci_R2 <- rename(Mean_ci_R2, mean = y)
Mean_ci_R2 <- rename(Mean_ci_R2, CI_low = ymin)
Mean_ci_R2 <- rename(Mean_ci_R2, CI_high = ymax)
rownames(Mean_ci_R2)[rownames(Mean_ci_R2) == "1"] <- "values"
R2_summary8 <- t(R2_summary8)
R2_summary8 <- as.data.frame(R2_summary8)
R2_summary8 <- merge(R2_summary8,Mean_ci_R2,by="mean")
rownames(R2_summary8)[rownames(R2_summary8) == "1"] <- "R2_lik"

#transform list AICc in data frame
AICc_PLR8_df <- data.frame(matrix(unlist(AICc_PLR8), nrow=length(AICc_PLR8), byrow=TRUE))
AICc_PLR8_df <- rename(AICc_PLR8_df, values = matrix.unlist.AICc_PLR8...nrow...length.AICc_PLR8...byrow...TRUE.)

#Calculate mean, max, min, sd and CIs of AICc
AICc_summary8 <- sapply(AICc_PLR8_df, function(AICc_PLR8_df) c( "min" = min(AICc_PLR8_df), 
                                                                  "max"= max(AICc_PLR8_df),
                                                                  "mean" = mean(AICc_PLR8_df),
                                                                  "sd_tree" = sd(AICc_PLR8_df)))

Mean_ci_AICc <- mean_ci(AICc_PLR8_df$values)
Mean_ci_AICc <- rename(Mean_ci_AICc, mean = y)
Mean_ci_AICc <- rename(Mean_ci_AICc, CI_low = ymin)
Mean_ci_AICc <- rename(Mean_ci_AICc, CI_high = ymax)
rownames(Mean_ci_AICc)[rownames(Mean_ci_AICc) == "1"] <- "values"
AICc_summary8 <- t(AICc_summary8)
AICc_summary8 <- as.data.frame(AICc_summary8)
AICc_summary8 <- merge(AICc_summary8,Mean_ci_AICc,by="mean")
rownames(AICc_summary8)[rownames(AICc_summary8) == "1"] <- "AICc"

#Add R2 and AICc to the other summ stats 
R2_summary8 <- rename(R2_summary8, mean.tree = mean)
R2_summary8 <- rename(R2_summary8, max.tree = max)
R2_summary8 <- rename(R2_summary8, min.tree = min)
R2_summary8 <- rename(R2_summary8, CI_low_tree = CI_low)
R2_summary8 <- rename(R2_summary8, CI_high_tree = CI_high)
AICc_summary8 <- rename(AICc_summary8, mean.tree = mean)
AICc_summary8 <- rename(AICc_summary8, max.tree = max)
AICc_summary8 <- rename(AICc_summary8, min.tree = min)
AICc_summary8 <- rename(AICc_summary8, CI_low_tree = CI_low)
AICc_summary8 <- rename(AICc_summary8, CI_high_tree = CI_high)

stats_PLR8 <- bind_rows(stats_PLR8, R2_summary8, AICc_summary8)
stats_PLR8 <- add_rownames(stats_PLR8, "VALUE")
stats_PLR8

#Convert in a table
gt_tbl8 <- gt(stats_PLR8)

gt_tbl8 <- gt_tbl8 %>% tab_header(
  title = "Model: P(threatened) ~ Body mass",
  subtitle = "n_species = 331; 100 DNA-only trees")

gt_tbl8

#Save the table
gtsave(gt_tbl8, filename = "Table_Summ_stats_PLR_P(threatened)_vs_Body_mass_phylo_intra_uncertainty_extant_pops_DNA_only_trees.html", path = "Results/PLRs")

#End of script

